export enum ProductStatus {
  UNSPECIFIED = 'UNSPECIFIED',
  PRE_ORDER = 'PRE_ORDER',
  NOT_YET_OPEN = 'NOT_YET_OPEN',
  OPEN_FOR_SALE = 'OPEN_FOR_SALE',
  SOLD_OUT = 'SOLD_OUT',
  CLOSED = 'CLOSED',
  DELETED = 'DELETED',
}
