networks:
  notification-network:
    driver: bridge

services:
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - notification-network

  app:
    build:
      context: ../..
      dockerfile: ./services/notification-service/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/creds.json
    volumes:
      - ./fmcdemo-32a22-e1c2cd5a5769.json:/app/creds.json
    ports:
      - "3004:3004"
      - "50054:50054"
    networks:
      - notification-network
    restart: unless-stopped

