export enum ErrorOrderCode {
    ERROR_CODE_UNSPECIFIED = 'ERROR_CODE_UNSPECIFIED',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    ADDRESS_UNREACHABLE = 'ADDRESS_UNREACHABLE',
    SHIPPING_PROVIDER_ERROR = 'SHIPPING_PROVIDER_ERROR',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

export enum ValidationErrorCode {
    VALIDATION_ERROR_CODE_UNSPECIFIED = 'VALIDATION_ERROR_CODE_UNSPECIFIED',
    NOT_FOUND = 'NOT_FOUND',
    OUT_OF_STOCK = 'OUT_OF_STOCK',
    
}