export enum SubOrderStatus {
    PENDING = 'PENDING',
    PAID = 'PAID',
    SHIPPED = 'SHIPPED',
    DELIVERED = 'DELIVERED',
    CANCELED = 'CANCELED',
    RETURNED = 'RETURNED',
    REFUNDED = 'REFUNDED',
}