services:
  app:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8080
      - PG_DATABASE_URL=postgresql://postgres:123@postgres:5432/communication
      - REDIS_URL=redis://redis:6379
    ports:
      - "8090:8080"
    # restart: unless-stopped

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: communication
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
