services:
  app:
    build:
      context: ../..
      dockerfile: ./services/communication-service/Dockerfile
    depends_on:
      - redis
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=3005
      - GRPC_SERVER_ADDRESS=0.0.0.0
      - GRPC_PORT=50055
      - PG_DATABASE_URL=postgresql://postgres:123@host.docker.internal/communication
      - REDIS_URL=redis://redis:6379
    ports:
      - "3005:3005"
      - "50055:50055"

  redis:
    image: redis:latest
